id: PB5046720
initial_creation_type: ocr
source_metadata:
  volumes:
    3548ebba86784058966565e9852235fb:
      base_file: v096.txt
      image_group_id: I1PD95941
      title: དྲི་མ་མེད་པ་རིན་པོ་ཆེའི་སྤྲིང་ཡིག།
      total_pages: 1144
      volume_number: 96
