id: D493A3E1E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:05:26+00:00'
last_modified: '2022-05-30T04:25:32.924339+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a13a:
      image_group_id: I1PD95941
      title: དྲི་མ་མེད་པ་རིན་པོ་ཆེའི་སྤྲིང་ཡིག།
      total_pages: 1144
      order: 96
      base_file: a13a.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
